### ISSUE TITLE
Rails Version

### ISSUE THREAD

**Issue by arena** [96ready/ready96#6]
This project has been criticized for having a very old version of Rails. Updating it would be nice and make adding new features or fixing bugs more sustainable.

**Comment by arena** [comment]
Hi @heatherm and @siruguri - Please comment and mention the other if either of you starts work on this in order to avoid duplicating any effort.

**Comment by arena** [comment]
@heatherm 
What are the current versions of Ruby and Rails used in this project. I'd like to make sure that the ReadMe is up to date.

**Comment by heatherm** [comment]
rails (3.2.13)
ruby 1.9.3-p551

**Comment by heatherm** [comment]
@arena you can find the ruby version in `https://github.com/96ready/ready96/blob/master/.ruby-version` and the rails version if you search for 'rails' inside `https://github.com/96ready/ready96/blob/master/Gemfile.lock`

**Comment by arena** [comment]
Thank you @heatherm 
I updated the readme on my branch and I will pull it into master soon.
