### ISSUE TITLE
Database connection for Plan Widget is overly complicated and unnecessary. 

### ISSUE THREAD

**Issue by arena** [96ready/ready96#9]
The content is no longer customized via a CMS in this fork, yet updating the plan widget is next to impossible for a user with only basic knowledge of HTML

**Comment by arena** [comment]
![image](https://cloud.githubusercontent.com/assets/411070/21446864/ce673716-c880-11e6-8c7a-001adb755490.png)

**Comment by heatherm** [comment]
@arena apologies. I missed this as I was working from issues in Trello. I brought back the db-based plans & admin plan setup which was given the OK from Jerry and is now merged.

Shall we move issues from Trello over to here?

**Comment by arena** [comment]
The widget looks so much better now!! Yay!!!
